### ISSUE TITLE
Review and fix configuration loading system

### ISSUE THREAD

**Issue by MrCreosote** [kbase/index_runner#123]
I'm a little confused about the 2 configuration options:
* GLOBAL_CONFIG_URL
  * Documented as `Set this to use a specific config release that will not automatically update.`
  * However, based on examination of the code, the file will be reloaded, by default, every 10m, and so the config will automatically update.
* GITHUB_RELEASE_URL
  * This will also be reloaded every 10m
  * It will also be reloaded every 1m *if the git tag for the release has changed*

The entire configuration, including all environment variables, is also reloaded every 10m or when the git tag of GITHUB_RELEASE_URL changes.

I guess I'm confused about the configuration update strategy:

* Is it really intended to reload the entire configuration every 10m? I can see reloading the external file, but reloading DB info, etc, seems dangerous.
* Should the config for GLOBAL_CONFIG_URL update or not?
* Is it necessary to reload the GITHUB_RELEASE_URL every 10m or just when the git tag changes? It seems like the latter would be satisfactory.

One other thing:
```
        'generic_shard_count': os.environ.get('GENERIC_SHARD_COUNT', 2),
        'generic_replica_count': os.environ.get('GENERIC_SHARD_COUNT', 1),
```
Should the latter be `GENERIC_REPLICA_COUNT`?

**Comment by jayrbolton** [comment]
Re: the last part, looks like that was a typo (we've maybe had some pr reviews recently that were too quick/cursory). Addressed in #129

**Comment by jayrbolton** [comment]
The config loading code was messed with at several points and may have gotten out of whack. Slebras was the person to work on it most recently so maybe he can answer some of this. Here is the intended functionality:

* One URL is supposed to be a general url to the base releases path, and should automatically update with new releases. Definitely does not need to be every 10 minutes, but every 1 hour should be good.
* The other URL is meant to be a fixed URL to a specific release tarball of a specific version, and should never change. Using this var,  you could for example set a prerelease config for CI in order to do testing, which would not affect prod.

**Comment by jayrbolton** [comment]
So the actionable thing here is we should review the logic of the config module and likely clean it up to meet the above two requirements, if they are out of whack.

**Comment by MrCreosote** [comment]
@slebras comments?

**Comment by MrCreosote** [comment]
Also what I'm hearing is that it's not necessary for the entire config to reload - just the external files - which makes sense to me

**Comment by MrCreosote** [comment]
OK, since there's no further comments I'm going to propose that:
1. We remove the 10m refresh of the configuration.
2. We remove the update for `GLOBAL_CONFIG_URL`.
3. We continue checking `GITHUB_RELEASE_URL` 1 / minute for release changes and update on release change.

Any objections? I'll take silence as consent on Monday afternoon.

**Comment by jayrbolton** [comment]
This is deployed. Also, it's further simplified to only use GLOBAL_CONFIG_URL now, and does not use the releases api anymore.
